project:
  type: website
  output-dir: docs

website:
  title: "quitezone"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About SHH
      - href: research.qmd
        text: Research

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false

editor: visual

